### ISSUE TITLE
" INFO  No publishable resources"  during v3 installation

### ISSUE THREAD

**Issue by scil** [lara-zeus/sky#130]
**Describe the bug**
encounter " INFO  No publishable resources" when  execute `php artisan vendor:publish"

**To Reproduce**
follow https://larazeus.com/docs/sky/v3/installation

1. `composer require lara-zeus/sky`  and  publish the migrations files
2. there resources not found
```
>php artisan vendor:publish --tag=zeus-sky-seeder

   INFO  No publishable resources for tag [zeus-sky-seeder].


>php artisan vendor:publish --tag=zeus-sky-factories

   INFO  No publishable resources for tag [zeus-sky-factories].


>php artisan vendor:publish --tag="filament-forms-tinyeditor-assets"

   INFO  No publishable resources for tag [filament-forms-tinyeditor-assets].


```

**Expected behavior**
the resources should exist.
 
**Desktop (please complete the following information):**
 - OS: windows

**Additional context**

```
    "require": {
        "php": "^8.1",
        "filament/filament": "^3.0-stable",
        "guzzlehttp/guzzle": "^7.2",
        "lara-zeus/sky": "^3.0@beta",
        "laravel/framework": "^10.10",
        "laravel/jetstream": "^3.3",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8"
    },

```

**Comment by atmonshi** [comment]
the documentation hasn't updated for v3; yet, still ongoing.
but the installation is similar to the upgrade prosses, and you can find it here:
https://larazeus.com/docs/core/v3/upgrade#content-registering-the-plugins

The seeders and factories are not available to be published in v3.
And you can publish the migration using:
`php artisan  vendor:publish --tag=zeus-sky-migrations`

**Comment by scil** [comment]
Thank you for your replay and your wonderful work!
