### ISSUE TITLE
It's not work after clean install

### ISSUE THREAD

**Issue by AndreyShakhtarin** [lara-zeus/sky#147]
**Describe the bug**
After clean install error dependencies

**To Reproduce**
1. composer create-project laravel/laravel
2. composer require filament/filament:"^3.0-stable" -W
3. composer require lara-zeus/sky

Problem 1
    - lara-zeus/sky[2.1.6, ..., 2.4.6] require filament/spatie-laravel-translatable-plugin ^2.0 -> satisfiable by filament/spatie-laravel-translatable-plugin[v2.4.50, ..., v2.17.53].
    - lara-zeus/sky[2.0.0, ..., 2.1.5] require lara-zeus/core dev-main -> found lara-zeus/core[2.0.0, ..., 2.x-dev, v3.0.0-beta1, ..., 3.x-dev] but it does not match the constraint.
    - lara-zeus/sky[2.4.7, ..., 2.4.34] require ryangjchandler/filament-navigation dev-with-rtl -> found ryangjchandler/filament-navigation[dev-dependabot/github_actions/ramsey/composer-install-2, dev-main, v0.1.0, ..., v0.5.0, v1.0.0-beta1, v1.0.0-beta2, v1.0.0-beta3, v1.0.0-beta4] but it does not match the constraint.

**Comment by atmonshi** [comment]
sky still in beta so you have to use:
`composer require lara-zeus/sky:"^3.0"`
or
`composer require lara-zeus/sky:"^3.0-dev"`

**Comment by tqt97** [comment]
i have same problem

**Comment by atmonshi** [comment]
@tqt97 did you try this?

> sky still in beta so you have to use: `composer require lara-zeus/sky:"^3.0"` or `composer require lara-zeus/sky:"^3.0-dev"`

**Comment by atmonshi** [comment]
you also have to add
`"minimum-stability": "dev",`

**Comment by tqt97** [comment]
> composer require lara-zeus/sky:"^3.0-dev"
> "minimum-stability": "dev",

I tried this and got error

**Comment by atmonshi** [comment]
now the [stable](https://github.com/lara-zeus/sky/releases/tag/v3.1.0) version has been released you can do composer update

feel free to reopen or create a new issue :)
