### ISSUE TITLE
[Bug]: could not find driver error 

### ISSUE THREAD

**Issue by TapanDerasari** [lara-zeus/sky#161]
### What happened?

As #158 explain here, when I try to open the posts, pages 

could not find driver
CREATE TABLE "post_statuses" ("id" integer PRIMARY key autoincrement NOT NULL, "name" varchar, "label" varchar, "class" varchar, "icon" varchar)

### How to reproduce the bug

Fresh installation of latest laravel 10.x and filament 3.x

then install the lara-zeus/sky

try to access urls:
admin/posts/*
admin/pages/*

### Package Version

3.1.3

### PHP Version

8.2.7

### Laravel Version

10.24.0

### Which operating systems does with happen with?

Linux

### Notes

I did enabled the redis-ext but still no luck.

Any help or suggestion would be great :)

**Comment by atmonshi** [comment]
if you print out
`phpinfo();` in any page `index.php` for example 

do you see the redis-ext ?

restarted apache or nginx ?

**Comment by badrshs** [comment]
got same error yesterday  on v2

**Comment by atmonshi** [comment]
I am using 

https://github.com/calebporzio/sushi

How It Works Under the hood, this package creates and caches an SQLite database JUST for this model. It creates a table and populates the rows. If for whatever reason, it can't cache a .sqlite file, it will default to using an in-memory sqlite database.

check this also
https://github.com/lara-zeus/bolt/issues/140#issuecomment-1688156159

maybe its folders permissions

**Comment by atmonshi** [comment]
@badrshs 
> got same error yesterday on v2

was it a fresh installation or an upgrade?

**Comment by TapanDerasari** [comment]
> if you print out `phpinfo();` in any page `index.php` for example
> 
> do you see the redis-ext ?
> 
> restarted apache or nginx ?

Yes it shows the redis as enabled

**Comment by atmonshi** [comment]
if you can install and use [sushi](https://github.com/calebporzio/sushi)

in your app without sky
and see if it runs fine?!

hard for me to debug...

operating system
PHP version
what extension you enable in php
apache or nginx
folders permissions 
other packages

**Comment by TapanDerasari** [comment]
@atmonshi thanks for the suggestion I tried the Sushi in fresh installation of laravel 10.x and separate project with Sky,

It creates the sushi model files and the `sushi-lara-zeus-sky-models-post-status.sqlite`. but still no luck.

Operating System: Ubuntu 
PHP 8.2
Apache with folder permission of 777

**Comment by badrshs** [comment]
Hi guys, Im getting same issue as reported but I'm on windows and I use mysql as  normal and fresh project .. 

you guys are talking on the redis , why I would even need that ? can't see at least anything in the documentation talking about it ..

**Comment by atmonshi** [comment]
@badrshs 


> I am using
> 
> https://github.com/calebporzio/sushi
> 
> How It Works Under the hood, this package creates and caches an SQLite database JUST for this model. It creates a table and populates the rows. If for whatever reason, it can't cache a .sqlite file, it will default to using an in-memory sqlite database.
> 
> check this also [lara-zeus/bolt#140 (comment)](https://github.com/lara-zeus/bolt/issues/140#issuecomment-1688156159)
> 
> maybe its folders permissions

**Comment by TapanDerasari** [comment]
@atmonshi @badrshs 

I did installed the Sushi, it seems like Now I can access the posts, pages etc...

But when there are no records in every resources navigation was working fine but after creation of one post, posts.index is inaccessible .

It gives **Route [post] not defined.**

**Comment by atmonshi** [comment]
@TapanDerasari can you share your config from `adminPanelProvider`

also run php artisan route:list to see if sky routes registered or not

**Comment by TapanDerasari** [comment]
@atmonshi Here is adminPanelProvider file that I configure after reviewing your demo app code.

AdminPanelProvider.php
`$panel->plugins($this->getPlugins());`

```
public function getPlugins(): array
    {
        return [
            SpatieLaravelTranslatablePlugin::make()
                ->defaultLocales(['en']),
            FilamentNavigation::make(),
            SkyPlugin::make(),
        ];
    }
```

and here is the route list result of posts routes
```
GET|HEAD   admin/posts ........................................................... filament.admin.resources.posts.index › LaraZeus\Sky › ListPosts
  GET|HEAD   admin/posts/create .................................................. filament.admin.resources.posts.create › LaraZeus\Sky › CreatePost
  GET|HEAD   admin/posts/{record}/edit ............................................... filament.admin.resources.posts.edit › LaraZeus\Sky › EditPost
```

Create and Edit pages are working but listing page of posts,library and pages not working.

Let me know if anything else requires..

**Comment by atmonshi** [comment]
Do you have more than one panel?
if so, try to add `SkyPlugin::make(),` to the other plugins for testing.

Can you check the file in your vendor folder? and it is the same as:
https://github.com/lara-zeus/sky/blob/3.x/routes/web.php

> and here is the route list result of posts routes

You should see something like:
`  GET|HEAD  sky/post/{slug} ............................................................ post › LaraZeus\Sky › Post`

**Comment by TapanDerasari** [comment]
Yes, I do have multiple panel and after adding the plugin code to the another panel It did started working.

also yes, both `web.php` files are identical.

In the route list now there are routes that you mentioned.

But I think this is a bug bcz I don't need the plugin functionality into my another panel. :)

**Comment by atmonshi** [comment]
yes, I will find a better way to handle the routes for the frontend, that is way I asked about the panels
I may add config file for the frontend options.

will be fixed in few days
thank you for the time to check this :)

**Comment by atmonshi** [comment]
New release to address the configuration for multiple panels.
I hope this will fix any issues.
Anyone facing new issues, please feel free to open new one :)

Thank you for using Sky.
