### ISSUE TITLE
[Bug]: Multiple panel FilamentNavigation issue

### ISSUE THREAD

**Issue by TapanDerasari** [lara-zeus/sky#167]
### What happened?

I am using multiple filament panel into my project.

It always ask me to register **FilamentNavigation** plugin into my other panel thought I don't require there. bcz the CMS should be manage by admin only.

### How to reproduce the bug

- Create a multiple panels into the project using filament panels.
- Do the configurations into the AdminPanelProvider.php but don't do the same in other panel providers file.

### Package Version

3.2.1

### PHP Version

8.2.7

### Laravel Version

10.26.0

**Comment by atmonshi** [comment]
the last version of sky should fix this issue
I tested it in new filament app with two different panels and each of them works fine

can you double check the version you have
`php artisan about`

and which page are you getting this error?
/app or /admin or in the frontend?

**Comment by atmonshi** [comment]
Let me know if you are still facing this issue by reopening this :)
