### ISSUE TITLE
Non-sequitur package names are confusing and cause extra mental overhead

### ISSUE THREAD

**Issue by btantlinger** [lara-zeus/sky#178]
Sky is pretty nice, and I hate to nitpick, but I find myself being frustrated by the naming of the various packages. I'm constantly having to go back to the project web page to figure out what the names mean.  Names like Sky, Bolt, Rain,  Aphrodite, etc  aren't really descriptive of anything a CMS does.  Worse still, these names are used throughout the configuration files, class names,  documentation etc causing extra mental overhead.  I don't want to have to think too much about what something is named.  Especially 6 months from now,  when I'll have to re-remember what all these names mean.

Would it make more sense to just call it Zeus Cms,  Zeus Form Builder, Zeus Layouts?  Maybe at least change the class names and configuration files to something descriptive of what it does.

**Comment by atmonshi** [comment]
Thank you for your feedback :)

When I started all this, I wasn't expecting anyone ever to use my packages. I created them to be used with my clients, and now here we are :)

I understand your point entirely. It's confusing, I know.

Changing the name is not that easy between the website, composer, filament plugins page, filament discord, the classes, and the config files (which will be breaking changes for everyone). 
And somehow, I have to maintain the old URLs to retain visitors and backlinks. Who knows what else I have to change :)

Do something like:
```php
//This is the CMS (sky)
SkyPlugin()->make()
```

I know this is not a solution :), but I can't do anything right now and will think of better ways in the future. And maybe slowly change the classes to reflect the package's purpose.  


thank you again for using the packages, and for your feedback.
