### ISSUE TITLE
Post page and page not work [Bug]: 

### ISSUE THREAD

**Issue by gcorp-llc** [lara-zeus/sky#192]
### What happened?

this post url and page show this error 
`
could not find driver
SELECT "label", "name" FROM "post_statuses"
`

### How to reproduce the bug

install and go to this url for post and page but faq and navigate ... is worked

### Package Version

latest

### PHP Version

8.3

### Laravel Version

10

### Which operating systems does with happen with?

Windows

**Comment by atmonshi** [comment]
as mentioned in the [docs](https://larazeus.com/docs/sky/v3/getting-started/installation#content-installation):
>Before starting, make sure you have the following PHP extensions enabled: **sqlite**

**Comment by gcorp-llc** [comment]
yes sqlite is active in laragon virtual but use mariadb and faq page and other is worke but show error for post and pages links

**Comment by atmonshi** [comment]
yes the `sqlite` only required on pages and posts since I am using [`https://usesushi.dev/`](https://usesushi.dev/)
similar issue: #161

**Comment by atmonshi** [comment]
check any other sqlite and redis related ext like pdo_sqlite or others depend on your system

**Comment by atmonshi** [comment]
sushi need: `"ext-sqlite3": "*",`

**Comment by gcorp-llc** [comment]
Thank you for your help, but I think it is better to delete the package and create the items myself
Maybe it would be better if the skin part was similar to the faq part of creating a mask so that these problems would not occur

**Comment by atmonshi** [comment]
np :)
