### ISSUE TITLE
[Bug]:  Method Filament\Tables\Columns\SpatieTagsColumn::hasRelationship does not exist.

### ISSUE THREAD

**Issue by retamayo** [lara-zeus/sky#198]
### What happened?

Followed install process in the docs (v3) 
Tried opening Posts resource but im getting this error

### How to reproduce the bug

 Dependency Version
-  "lara-zeus/sky": "^3.4",
- "laravel/framework": "^10.10",
- "filament/filament": "3.2",

Steps
- Install plugin according to navigation
- Open Post or Library Resource

### Package Version

3.4

### PHP Version

8.3

### Laravel Version

10.10

### Which operating systems does with happen with?

Windows

**Comment by atmonshi** [comment]
I cant reproduce this issue unfortunately.
did a new installation on laravel 10.10 and new filament 3.2 and sky 3.4

can you run php artisan about to get the exact versions?
maybe run composer update
also are you using `filament/spatie-laravel-tags-plugin` make sure it is in the same version as filament.

**Comment by arbet** [comment]
I am having the same issue after running composer update, and I am using the latest version of both filament and spatie laravel tags

I checked the method and it is actually not present in version 3.2.50

**Comment by atmonshi** [comment]
gonna need more information guys :)

one solution I found in discord thats worked for others:

"Your filament/filament version is 3.1.8 while the subpackages (filament/spatie-laravel-media-library-plugin) are on v3.2.37
Please constrain all filament packages to ^3.2 and run composer update to update the packages to the correct version"
