### ISSUE TITLE
Make it possible to disable frontend

### ISSUE THREAD

**Issue by rabol** [lara-zeus/sky#210]
**Describe the on you'd like**

Even though the frontend scaffolding is a nice and easy way to get up and running, it would be nice with the possibility to disable all Sky's frontend routes

**Comment by atmonshi** [comment]
please update and set the config:
`'headless' => true,`

let me know if there is any bugs

**Comment by rabol** [comment]
cool, thanks

something like 

```
 'headless' => env('SKY_HEADLESS', 'false),
```

would be super nice

**Comment by atmonshi** [comment]
`env` support also coming with v4.

**Comment by rabol** [comment]
And when is v4

**Comment by atmonshi** [comment]
dont know :)

sky v4 will be out after filament v4, 
filament v4 will be out after tailwind 4, 
I dont know when v4 will be released :)

but I am expecting sky v4 will be released mid/late jan 25

looks simple to add `env` support, but there will be refactoring for the configuration that will make breaking changes, thats why I dont want to do it now.
also looks wired to add one `env` for `headless` and not the other options.

is publishing the sky configuration and set the `headless` option causing any issues?
