### ISSUE TITLE
[Bug]: Cannot install on a new clean jetstreem app

### ISSUE THREAD

**Issue by rabol** [lara-zeus/sky#211]
### What happened?

Cannot install Sky on a new Laravel app

### How to reproduce the bug

laravel app installed via Herd, with Jetstream and livewire, then installed Filament,

then execute:

```
composer require lara-zeus/sky  
```

The I got this error:
```
 Problem 1
    - lara-zeus/sky[2.0.0, ..., 2.1.1] require lara-zeus/core dev-main -> found lara-zeus/core[dev-globally-searchable, 2.0.0, ..., 2.x-dev, v3.0.0-beta1, ..., 3.x-dev] but it does not match the constraint.
    - lara-zeus/sky[2.1.2, ..., 2.4.34] require doctrine/dbal ^3.3 -> found doctrine/dbal[3.3.0, ..., 3.9.1] but the package is fixed to 4.1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - lara-zeus/sky[v3.1.0, ..., v3.4.11] require doctrine/dbal ^3.5.1 -> found doctrine/dbal[3.5.1, ..., 3.9.1] but the package is fixed to 4.1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires lara-zeus/sky * -> satisfiable by lara-zeus/sky[2.0.0, ..., 2.4.34, v3.1.0, ..., v3.4.11].
```

### Package Version

N/A

### PHP Version

8.3.12

### Laravel Version

11.25.0

### Which operating systems does with happen with?

macOS

**Comment by atmonshi** [comment]
do you have the `doctrine/dbal` in your composer?
I'll check too with new laravel app
try
`composer require lara-zeus/sky -W`

**Comment by atmonshi** [comment]
yes I got the same error, will update soon
meanwhile you can run `composer require lara-zeus/sky -W` and it will work.

**Comment by atmonshi** [comment]
cant drop the support for `doctrine` till v4 next year :)
