### ISSUE TITLE
[Bug]: Pages resource says Posts

### ISSUE THREAD

**Issue by rabol** [lara-zeus/sky#213]
### What happened?

The pages resource say that one is creating a new post

### How to reproduce the bug

just try to create a new page
<img width="460" alt="Screen Shot 2024-09-29 at 18 03 54" src="https://github.com/user-attachments/assets/e0f37e97-3ee6-4618-9e27-07d6b71c3502">

### Package Version

3.4.12

### PHP Version

8.3.12

### Laravel Version

11.25.0

### Which operating systems does with happen with?

macOS

**Comment by atmonshi** [comment]
I would appreciate it if you can send a PR for this, you can even do it from github site itself by editing [this file](https://github.com/lara-zeus/sky/blob/3.x/src/Filament/Resources/PageResource.php) :)
