### ISSUE TITLE
[Bug]: could not find driver 

### ISSUE THREAD

**Issue by fazliddin** [lara-zeus/sky#217]
### What happened?

![image](https://github.com/user-attachments/assets/3480f05a-4ddd-495b-811c-441f206019d4)

### How to reproduce the bug

At first load after install

### Package Version

3

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by atmonshi** [comment]
similar to #161, can you make sure you have `SQLite` ext in php enabled

**Comment by fazliddin** [comment]
in my project mysql is enabled

**Comment by atmonshi** [comment]
you will need `SQLite` as I mentioned because we use https://usesushi.dev/, 

and you can read more about it in the link I sent you.

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
