### ISSUE TITLE
Method ViewColumn::tooltip does not exist Error

### ISSUE THREAD

**Issue by vijayrana99** [lara-zeus/sky#24]
I recently installed this package on fresh filament installation. When I visit the `posts` and `pages` page, it is showing me the following error. Can anyone please help on this?

`
Method Filament\Tables\Columns\ViewColumn::tooltip does not exist.

`
![image](https://user-images.githubusercontent.com/7912330/178128820-7c66fbae-9c2e-4060-83f4-707b9cf8167f.png)

**Comment by atmonshi** [comment]
which version of filament do you have?
I cant reproduce the issue

**Comment by vijayrana99** [comment]
You may close the issue. It's fixed. It looks like there was a mis-configuration
