### ISSUE TITLE
Installation error encountered

### ISSUE THREAD

**Issue by mcfaith9** [lara-zeus/sky#53]
I tried to add this on my project using composer `composer require lara-zeus/sky`

and I encountered this I am using Laravel 8, php 8, filament v2

![image](https://user-images.githubusercontent.com/34260281/198350450-5646de2d-7b6a-4277-bcb6-ee298479559d.png)

**Comment by atmonshi** [comment]
try `composer require lara-zeus/sky -W`
to update all dependencies, I am using:
`"filament/spatie-laravel-translatable-plugin": "^2.0",`

**Comment by mcfaith9** [comment]
Thank you for the replies I did try it `composer require lara-zeus/sky -W` and also `composer require lara-zeus/sky:*` but I still getting same error, I did try to upgrade some dependencies version but still havent successfully installed it

**Comment by mcfaith9** [comment]
since `filament` upgraded to `v2 ` I have encountered a lot of installation problem on their plugins

**Comment by atmonshi** [comment]
you have to make sure you installed the compatible version of all the packages that sky depend on them
check:

```
        "doctrine/dbal": "^3.3",

        "filament/spatie-laravel-media-library-plugin": "^2.0",
        "filament/spatie-laravel-tags-plugin": "^2.0",
        "filament/spatie-laravel-translatable-plugin": "^2.0",

        "mohamedsabil83/filament-forms-tinyeditor": "^1.5",
        "spatie/laravel-medialibrary": "^10.0.0",
        "spatie/laravel-sluggable": "^3.3",
        "spatie/laravel-tags": "^4.0"
        "archtechx/laravel-seo": "^0.5",
        "calebporzio/sushi": "^2.4",
        "codeat3/blade-iconpark": "^1.4",
        "filament/filament": "^2.16",
        "filament/notifications": "^2.0",
```

if you already installed any of these packages, make sure to upgrade them manually before installing sky

also if you can share the last error message

**Comment by atmonshi** [comment]
closing, let me know if you still having issues.
