### ISSUE TITLE
[Minor Issue]  Usability Change I would Request

### ISSUE THREAD

**Issue by jeremiahsherrill** [lara-zeus/sky#95]
When you go to the page or the post and they are not published you are presented with a linking title, if the page is not published, you are directed to a page that "doesn't exist"   I would include a check to if the page is published and if not the link should either not exist or go to the edit page.  It confused me for a few moments.   Also it should probably go to the edit page anyway for all post types, and include a button with an arrow or something that allows you to visit the page.

**Comment by atmonshi** [comment]
Yes, To be honest, that was bugging me, too :). I will address this in the next release.

Thanks for reporting.

**Comment by atmonshi** [comment]
fixed in the last release 👍
