### ISSUE TITLE
[ Feature Request ]  insertion of forms from bolt into pages

### ISSUE THREAD

**Issue by jeremiahsherrill** [lara-zeus/sky#96]
This would be incredibly amazing, especially from a CMS standpoint.

**Comment by atmonshi** [comment]
I hope you mean something like this:
https://demo.larazeus.com/bolt
which has already been implemented 

Otherwise, I am gonna ask you to explain some more :)

**Comment by jeremiahsherrill** [comment]
I mean that links to the form, but I am think rendering the form   you would have something like a short tag like wordpress does that would then render the form on the page.

**Comment by atmonshi** [comment]
ahh I see now, ok that will be a great addone to sky.
will look into it.

**Comment by atmonshi** [comment]
I implemented the feature, needed some testing.
If you can, install the branch `dev-bolt-parser` and try it.

Any feedback you can give me is welcome.

**Comment by jeremiahsherrill** [comment]
I will try to find time over the next couple days to test

**Comment by atmonshi** [comment]
Tested, and all good 👍
I also added a tab in forms to let users copy and paste.
Of course, it will be visible only if you install Sky with Bolt :)

<img width="1165" alt="Screenshot 2023-07-14 at 6 26 23 PM" src="https://github.com/lara-zeus/sky/assets/1952412/5b62af0f-ac6b-46c7-ae29-af01975a9976">
